"""
adversarial.py — Logic Collapse Horizon
=========================================
Adversarial robustness evaluation: FGSM and PGD-10 attacks.

Implements the adversarial vulnerability analysis from Paper Section 4.3.2,
which demonstrates that Logic-Collapsed models exhibit elevated adversarial
vulnerability — linking attribution fidelity to robustness.

Key finding (Table 4):
  Logic-Collapsed methods (Prune-70%, KD) show adversarial accuracy drops
  up to 2.3x larger than LoRA-SHAP under FGSM epsilon=0.1.
  LoRA-SHAP incurs the smallest drop under all attack settings.

Usage:
    from src.adversarial import fgsm_attack, pgd_attack, evaluate_adversarial
    results = evaluate_adversarial(model, loader, epsilons=[0.01, 0.1])
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from typing import Dict, List


# ── FGSM ──────────────────────────────────────────────────────────────────

def fgsm_attack(
    model:   nn.Module,
    X:       torch.Tensor,
    y:       torch.Tensor,
    epsilon: float,
) -> torch.Tensor:
    """
    Fast Gradient Sign Method (Goodfellow et al., 2014).

    x_adv = x + epsilon * sign( grad_{x} L(f(x), y) )

    Args:
        model   : target model (eval mode)
        X       : clean input (N, D)
        y       : true labels (N,)
        epsilon : perturbation magnitude

    Returns:
        x_adv : adversarial examples (N, D), clamped to [-3, 3]
    """
    model.eval()
    Xc = X.clone().float().detach().requires_grad_(True)
    loss = F.cross_entropy(model(Xc), y.long())
    loss.backward()
    x_adv = Xc + epsilon * Xc.grad.sign()
    return x_adv.detach().clamp(-3.0, 3.0)


# ── PGD ───────────────────────────────────────────────────────────────────

def pgd_attack(
    model:   nn.Module,
    X:       torch.Tensor,
    y:       torch.Tensor,
    epsilon: float,
    n_steps: int   = 10,
    alpha:   float = None,
) -> torch.Tensor:
    """
    Projected Gradient Descent attack (Madry et al., 2018).

    Iterative version of FGSM with step size alpha = 2.5 * epsilon / n_steps.

    Args:
        model   : target model (eval mode)
        X       : clean input (N, D)
        y       : true labels (N,)
        epsilon : perturbation budget
        n_steps : number of PGD steps (default 10, matching paper's PGD-10)
        alpha   : step size (default 2.5 * epsilon / n_steps)

    Returns:
        x_adv : adversarial examples (N, D)
    """
    if alpha is None:
        alpha = 2.5 * epsilon / n_steps

    model.eval()
    x_adv = X.clone().float().detach()
    x_adv = x_adv + torch.zeros_like(x_adv).uniform_(-epsilon, epsilon)

    for _ in range(n_steps):
        x_adv = x_adv.detach().requires_grad_(True)
        loss  = F.cross_entropy(model(x_adv), y.long())
        loss.backward()
        x_adv = x_adv + alpha * x_adv.grad.sign()
        # Project back into epsilon-ball around clean X
        delta = torch.clamp(x_adv - X, min=-epsilon, max=epsilon)
        x_adv = (X + delta).detach().clamp(-3.0, 3.0)

    return x_adv


# ── Evaluation ────────────────────────────────────────────────────────────

@torch.no_grad()
def _clean_accuracy(model: nn.Module, loader: DataLoader) -> float:
    model.eval()
    correct = total = 0
    for X, y in loader:
        preds    = model(X.float()).argmax(1)
        correct += (preds == y.long()).sum().item()
        total   += len(y)
    return round(correct / total, 4) if total > 0 else 0.0


def _adv_accuracy(
    model:      nn.Module,
    loader:     DataLoader,
    attack_fn,
    epsilon:    float,
) -> float:
    """
    Evaluate model accuracy on adversarial examples generated by attack_fn.
    """
    model.eval()
    correct = total = 0
    for X, y in loader:
        X_adv    = attack_fn(model, X.float(), y.long(), epsilon)
        with torch.no_grad():
            preds = model(X_adv).argmax(1)
        correct += (preds == y.long()).sum().item()
        total   += len(y)
    return round(correct / total, 4) if total > 0 else 0.0


def evaluate_adversarial(
    model:    nn.Module,
    loader:   DataLoader,
    epsilons: List[float] = None,
    pgd_steps: int = 10,
) -> Dict:
    """
    Full adversarial evaluation under FGSM and PGD-10.

    Matches the evaluation protocol in Paper Table 4:
        epsilon in {0.01, 0.1} for both FGSM and PGD.

    Args:
        model    : model to evaluate
        loader   : test DataLoader
        epsilons : list of epsilon values (default [0.01, 0.1])
        pgd_steps: PGD iteration count (default 10)

    Returns:
        dict with clean accuracy and accuracy-drop for each attack/epsilon pair
    """
    if epsilons is None:
        epsilons = [0.01, 0.1]

    clean_acc = _clean_accuracy(model, loader)
    results   = {"clean_acc": clean_acc}

    for eps in epsilons:
        fgsm_acc = _adv_accuracy(
            model, loader,
            lambda m, X, y, e: fgsm_attack(m, X, y, e),
            epsilon=eps,
        )
        pgd_acc = _adv_accuracy(
            model, loader,
            lambda m, X, y, e: pgd_attack(m, X, y, e, n_steps=pgd_steps),
            epsilon=eps,
        )
        results[f"fgsm_eps{eps}_acc"]  = fgsm_acc
        results[f"fgsm_eps{eps}_drop"] = round(clean_acc - fgsm_acc, 4)
        results[f"pgd_eps{eps}_acc"]   = pgd_acc
        results[f"pgd_eps{eps}_drop"]  = round(clean_acc - pgd_acc, 4)

    _print_results(results, epsilons)
    return results


def _print_results(results: Dict, epsilons: List[float]) -> None:
    print(f"  Clean acc : {results['clean_acc']:.4f}")
    for eps in epsilons:
        fd = results[f'fgsm_eps{eps}_drop']
        pd = results[f'pgd_eps{eps}_drop']
        print(f"  eps={eps:4.2f}  FGSM drop={fd:.4f}  PGD drop={pd:.4f}")
